#!/bin/bash
#PATH=/home/rnentjes/Programming/apitrace/build/:$PATH

rm -f ./TestScreen

nimrod c -d:useRealtimeGC --parallelBuild:0 -r TestScreen.nim

#apitrace trace ./LotsOfTriangles
# ./LotsOfTriangles