#!/bin/bash
#PATH=/home/rnentjes/Programming/apitrace/build/:$PATH

rm -f ./shooter

nimrod c -d:useRealtimeGC -d:release --parallelBuild:0 --deadCodeElim:on --opt:speed -r src/shooter.nim -o shooter

#apitrace trace ./LotsOfTriangles
# ./LotsOfTriangles